### PR TITLE
feat(provider): Telegram Provider🚀 Feature: #2409

### LINKED ISSUE #2409: Telegram Provider🚀 Feature:
### 🔖 Feature description

Can we create telegram provider that can send messages to telegram channel/group? something similar to Discord provider

### 🎤 Why is this feature needed ?

This can help users to send notifications to telegram channels/groups.. 

### ✌️ How do you aim to achieve this?

https://www.analyticsvidhya.com/blog/2022/07/sending-telegram-messages-made-easier-with-telegram-bot/

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by tsssdev**
### What change does this PR introduce?

New telegram provider

### Why was this change needed?
 Closes #2409

### CODE REVIEW

**Comment by tsssdev** [comment]
Hey guys, any one planning to review these changes? if so I can resolve conflicts.. right now it is tagged as beta, if needed we can tag it as alpha/experimental and release and get feedback from users?

**Comment by tsssdev** [comment]
Another suggestion is introducing community providers concept, so when ever we are not confident then those providers can be released through community providers and after we get traction and provider is stable then can be promoted to main branch?

**Comment by jainpawan21** [comment]
@tsssdev gentle reminder!

**Comment by p-fernandez** [comment]
Closing for inactivity. Feel free to reopen it in the future if able to address the changes requested and to adapt to current version.

**Comment by scopsy** [comment]
Telegram support was added in https://github.com/novuhq/novu/pull/11112 and will be available in the next minor release 🙏

**Pull request closed without merging**
