### PR TITLE
fix(root): add IS_WORKFLOW_PREFERENCES_ENABLED variable

### PR DESCRIPTION
**Pull request by jainpawan21**
### What changed? Why was the change needed?

- Add `IS_WORKFLOW_PREFERENCES_ENABLED` variable in worker image to resolve the feature flag error. That error will be fixed by [this PR](https://github.com/novuhq/novu/pull/6636)

### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Special notes for your reviewer

</details>

### CODE REVIEW

**Comment by SokratisVidros** [comment]
@jainpawan21 This PR will be obsolete as soon as we merge [this](https://github.com/novuhq/novu/pull/6757). The plan is to merge it by the end of this week.

**Comment by jainpawan21** [comment]
> @jainpawan21 This PR will be obsolete as soon as we merge [this](https://github.com/novuhq/novu/pull/6757). The plan is to merge it by the end of this week.

@SokratisVidros 

After that PR merge, this issue will still be there until we release new docker images. This is a temporary urgent fix for community self host users

**Comment by SokratisVidros** [comment]
> > @jainpawan21 This PR will be obsolete as soon as we merge [this](https://github.com/novuhq/novu/pull/6757). The plan is to merge it by the end of this week.
> 
> @SokratisVidros
> 
> After that PR merge, this issue will remain until we release new docker images. This is a temporary urgent fix for community self-host users

We will do an OS release immediately after we merge the feature flag PR.

**Comment by jainpawan21** [comment]
Waiting for the above PR merge and new docker images release 🙂 . Lets keep this PR opened, so that I can refer users to this PR.

**Comment by SokratisVidros** [comment]
I am closing this PR as [this change](https://github.com/novuhq/novu/pull/6636) is now merged. We will do a new Community Release, next week.

**Pull request closed without merging**
