### PR TITLE
feat(provider): Telegram Provider🚀 Feature: #2409

### LINKED ISSUE #2409: Telegram Provider🚀 Feature:
### 🔖 Feature description

Can we create telegram provider that can send messages to telegram channel/group? something similar to Discord provider

### 🎤 Why is this feature needed ?

This can help users to send notifications to telegram channels/groups.. 

### ✌️ How do you aim to achieve this?

https://www.analyticsvidhya.com/blog/2022/07/sending-telegram-messages-made-easier-with-telegram-bot/

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

Yes I am willing to submit a PR!

### PR DESCRIPTION
**Pull request by s00d**
### What change does this PR introduce?
New telegram provider

### Why was this change needed?
Closes https://github.com/novuhq/novu/issues/2409

### Other information (Screenshots)
I just updated the code to the latest version, thanks @tsssdev for the code

### CODE REVIEW

**Comment by davidsoderberg** [comment]
@s00d please provider screenshots of how it looks with the multi provider config edit line 34 to true in `apps/web/src/hooks/useFeatureFlags.ts` to see it in integrations.

**Comment by s00d** [comment]
FireShot Capture 013 - Integrations - Novu Manage Platform - localhost
FireShot Capture 014 - Integrations - Novu Manage Platform - localhost

This? added a round icon

**Comment by pavekovt** [comment]
Can someone review it?

**Comment by scopsy** [comment]
Telegram support was added in https://github.com/novuhq/novu/pull/11112 and will be available in the next minor release 🙏

**Pull request closed without merging**
