### PR TITLE
docs: add default novu providers article

### PR DESCRIPTION
**Pull request by sumitsaurabh927**
### What change does this PR introduce?

Adds an article explaining our default providers and states that they are for evaluation only.

### Why was this change needed?

There was no article on this topic as such and it was confusing

### Other information (Screenshots)

Fixes [this](https://linear.app/novu/issue/NV-2550/📡-add-an-article-about-the-novu-providers-email-and-sms) issue on linear.

https://github.com/novuhq/novu/assets/62152915/a99039ad-129b-4977-8164-c8445e4d0fbb

### CODE REVIEW

**Review by Susmita-Dey — COMMENTED** [review]
LGTM

**Comment by scopsy** [comment]
@sumitsaurabh927 I'm wondering if it would be better to put it under the "Channels" section? @unicodeveloper wdyt?

**Comment by sumitsaurabh927** [comment]
> @sumitsaurabh927 I'm wondering if it would be better to put it under the "Channels" section? @unicodeveloper wdyt?

Makes sense @scopsy 
Shall I move it under 'Channels', @unicodeveloper ?

**Comment by scopsy** [comment]
Closing as docs have been removed from the repo

**Pull request closed without merging**
