### PR TITLE
fix(root): update imports to use 'type' keyword for TypeScript consistency

### PR DESCRIPTION
**Pull request by merrcury**
### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Special notes for your reviewer

</details>

### CODE REVIEW

**Comment by SokratisVidros** [comment]
@merrcury, which tool did we use to do this? We should add it as a pre-save or pre-commit hook so that the codebase remains consistent.

**Review by SokratisVidros — APPROVED** [review]

**Comment by merrcury** [comment]
> @merrcury, which tool did we use to do this? We should add it as a pre-save or pre-commit hook so that the codebase remains consistent.

I used pnpm lint --fix

**Comment by merrcury** [comment]
But sometimes it does give issues with ENUM and all

**Comment by SokratisVidros** [comment]
@merrcury feel free to merge this.

**Comment by merrcury** [comment]
Opening a new one for this. This require lot of rebasing

**Pull request closed without merging**
