### PR TITLE
Demo web application

### LINKED ISSUE #288: [RLD-111] - Demo Web Application
## Why?

In order to demonstrate to the user how easy and flawless the flow is.

## How?

Open the browser and send to the widget the cient.

### PR DESCRIPTION
**Pull request by djabarovgeorge**
Closes #288

### CODE REVIEW

**Comment by scopsy** [comment]
@djabarovgeorge is this the final PR? or you need to merge branches to this one?

**Comment by djabarovgeorge** [comment]
@scopsy Nope, all the branches are merged to this one and the current branch is ready to be merged to main.

**Review by scopsy — APPROVED** [review]
Fantastish! Let me know when we can do a session together to to it on my machine :)

**Comment by djabarovgeorge** [comment]
Sure no problem let me just finish with branch - RLD-120-Test-notification-template
and we will be ready to go

**Pull request merged**
