### PR TITLE
refactor: update reactflow

### PR DESCRIPTION
**Pull request by davidsoderberg**
### What change does this PR introduce?
Updates react flow to latest version.

### Why was this change needed?
Because we have not updated it since we installed it first time.

### CODE REVIEW

**Review by p-fernandez — APPROVED** [review]
👏🏻

**Review by scopsy — APPROVED** [review]
🔥

**Comment by LetItRock** [comment]
@davidsoderberg @djabarovgeorge 
the `useStartFromScratchTour` hook has a selector for a DOM node with `[class="react-flow__controls"]` but because we've updated the library there is no such DOM node anymore... we should update it to `[data-testid="rf__controls"]` or something else, because I'm not sure if it's ok to rely on the library `data-testid` attribute

**Comment by davidsoderberg** [comment]
Closing this for now because a lot of stuff have happend since April and it is easier to do a new PR instead.

**Pull request closed without merging**
