### PR TITLE
feat(js): Pixel perfect implementation

### PR DESCRIPTION
**Pull request by desiprisg**
### Screenshots

<details>
<summary><strong>Expand for optional sections</strong></summary>

### Special notes for your reviewer

</details>

### CODE REVIEW

**Review by LetItRock — CHANGES_REQUESTED** [review]
:( 

Screenshot 2024-08-22 at 18 43 04

**Comment by desiprisg** [comment]
@LetItRock  I think this is the result of the issue we were talking about. There's an issue with the `build:watch` script. I keep getting the behaviour too. I think you'll see that some classes don't correspond to styles when inspecting. You'll need to build from scratch locally.

**Comment by LetItRock** [comment]
> @LetItRock I think this is the result of the issue we were talking about. There's an issue with the `build:watch` script. I keep getting the behaviour too. I think you'll see that some classes don't correspond to styles when inspecting. You'll need to build from scratch locally.

ok, it's weird, I tested it the first time by rebuilding everything, but now I don't see the issue anymore.

**Review by LetItRock — APPROVED** [review]
awesome! 🙌

**Pull request merged**
