### PR TITLE
fix: message for triggering notification

### PR DESCRIPTION
**Pull request by Ananya2001-an**
### What change does this PR introduce?

Fixed a small typo in the message shown after we connect our app. It was missing a word, probably "bell", as it seems from reading the complete sentence.  

### Other information (Screenshots)
image

### CODE REVIEW

**Comment by jainpawan21** [comment]
Good Catch 🎉

**Comment by Ananya2001-an** [comment]
> Good Catch 🎉

Thanks @jainpawan21

**Review by ainouzgali — APPROVED** [review]
⭐️ Thanks @Ananya2001-an !

**Comment by Ananya2001-an** [comment]
> ⭐️ Thanks @Ananya2001-an !

Hoping to make more contributions to **novu** 😄

**Pull request merged**
