### PR TITLE
Feat eazy sms

### LINKED ISSUE #5195: 🚀 Feature: Add a new provider for sms (Eazy)
### 🔖 Feature description

Add a new provider for SMS called 'Eazy'. You can find more [here](https://www.eazy.im/)

### 🎤 Why is this feature needed ?

requested by a [community member](https://discord.com/channels/895029566685462578/937309213036785744/1207334363444805674)

### ✌️ How do you aim to achieve this?

The outcome from this would be Novu supporting Eazy for SMS notifications

### 🔄️ Additional Information

_No response_

### 👀 Have you spent some time to check if this feature request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/novuhq/novu/blob/main/CONTRIBUTING.md)

### Are you willing to submit PR?

None

### PR DESCRIPTION
**Pull request by sr-26**
### What change does this PR introduce?

Closes #5195 

### Why was this change needed?

New Sms Provider.

### Other information (Screenshots)

image
image

### CODE REVIEW

**Comment by ainouzgali** [comment]
@coderabbitai review

**Review by BiswaViraj — CHANGES_REQUESTED** [review]
Please add the provider to [this file](https://github.com/novuhq/novu/blob/22f28801ff0a362b775a5b7863dda55721e7537a/apps/web/src/pages/integrations/components/multi-provider/sort-providers.ts#L77)

**Review by BiswaViraj — APPROVED** [review]

**Review by BiswaViraj — CHANGES_REQUESTED** [review]
@sr-26 Can you please fix the pipeline errors?
You'll need to add the failing words in the `.cspell` file
and also need to regenerate the pnpm.lock file by running `pnpm i`

**Comment by BiswaViraj** [comment]
> Added @BiswaViraj, the package.lock has significant version changes. Is this okay?

Yes, it is fine

**Review by BiswaViraj — APPROVED** [review]

**Pull request merged**
