### PR TITLE
[RLD-23] - Checkbox component

### PR DESCRIPTION
**Pull request by rockingrohit9639**
## Why?

We are in the process of creating our new core components using [mantine](https://mantine.dev/core/checkbox/) and creating our very own [storybook](https://storybook.js.org/docs/react/get-started/introduction) for easier UI development. 

To learn more about our design system see [https://github.com/notifirehq/notifire/issues/219](https://github.com/notifirehq/notifire/issues/219)

## How?

To start contributing you need to run storybook locally:

```
npm run setup:project
cd apps/web 
npm run storybook
```

To contribute, add a new component directory named `checkbox` in `apps/web/src/design-system/` with the following files: 

1\. Component file, overriding Mantine’s default implementation based on the design below. 

2\. Styles implementation, to fit our design. Consider dark and light color scheme. 

3\. Create a story for the checkbox component, showcasing our designs options (Checked, and un-checked). 

### Checkbox designs

Checkbox dark scheme:

[Checkbox - Relayed Design System (Figma)](https://www.figma.com/file/KprcTdnkZz0bxFepI8ZSHP/Relayed-Design-System?node-id=529%3A1593)

Checkbox light scheme:

[Checkbox - Relayed Design System (Figma)](https://www.figma.com/file/KprcTdnkZz0bxFepI8ZSHP/Relayed-Design-System?node-id=529%3A1609)

> See the [Button](https://github.com/notifirehq/notifire/tree/master/apps/web/src/design-system/button) component for an implementation example.

## Need help?

For any questions feel free to contact us on [discord](https://discord.gg/vh6N694qMa) 😃

### CODE REVIEW

**Review by ainouzgali — COMMENTED** [review]
@[rockingrohit9639](https://github.com/rockingrohit9639) thank you for contributing!! 
Amazing work, I really loved your initiative :)
Just please check out the comments about the deign details :) 
Let me know if you need anything :)

**Comment by rockingrohit9639** [comment]
> @[rockingrohit9639](https://github.com/rockingrohit9639) thank you for contributing!! Amazing work, I really loved your initiative :) Just please check out the comments about the deign details. Let me know if you need anything

Okay @ainouzgali I will do all the required changes.

**Review by ainouzgali — COMMENTED** [review]
Looks greattt! 
just that change in background please 
thank you :)))

**Comment by rockingrohit9639** [comment]
@ainouzgali I have done all the required changes. Please have a look and merge if possible.

**Review by ainouzgali — APPROVED** [review]

**Comment by ainouzgali** [comment]
@rockingrohit9639  Great job on your first pr!! Thank you for contributing 🎉⭐️

**Pull request merged**
